fix: update Nginx installation method and add expected fingerprint verification in Dockerfiles

diff --git a/tests/linux/Dockerfile-debian b/tests/linux/Dockerfile-debian
--- a/tests/linux/Dockerfile-debian
+++ b/tests/linux/Dockerfile-debian
@@ -4,6 +4,7 @@ ENV container=docker
 ENV LC_ALL=C
 ENV DEBIAN_FRONTEND=noninteractive
 ENV NGINX_VERSION=1.28.0
+ENV EXPECTED_FPR=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
 
 RUN apt-get update \
     && apt-get install -y systemd systemd-sysv \
@@ -25,11 +26,12 @@ RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
 
 RUN apt update && \
     apt-get install php-fpm curl gnupg2 ca-certificates python3-pip -y && \
-    echo "deb https://nginx.org/packages/debian/ bookworm nginx" > /etc/apt/sources.list.d/nginx.list && \
-    echo "deb-src https://nginx.org/packages/debian/ bookworm nginx" >> /etc/apt/sources.list.d/nginx.list && \
-    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62 && \
+    curl -fsSL https://nginx.org/keys/nginx_signing.key | gpg --dearmor --output /usr/share/keyrings/nginx-archive-keyring.gpg && \
+    gpg --batch --no-default-keyring --keyring /usr/share/keyrings/nginx-archive-keyring.gpg --list-keys --with-colons | awk -F: '/^fpr:/ { print $10 }' | grep -qx "$EXPECTED_FPR" || { echo "ERROR: expected fingerprint $EXPECTED_FPR not found in keyring" >&2; exit 1; } && \
+    . /etc/os-release && \
+    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://nginx.org/packages/${OS} ${VERSION_CODENAME} nginx" | tee /etc/apt/sources.list.d/nginx.list && \
     apt-get update && \
-    apt-get install -y --no-install-recommends nginx=${NGINX_VERSION}-1~bookworm
+    apt-get install -y --no-install-recommends nginx=${NGINX_VERSION}-1~${VERSION_CODENAME}
 
 COPY ./package-debian/*.deb /opt
 
